[package]
name = "bzip2-js"
version = "1.0.0"
authors = ["planet0104 <planet0104@gmail.com>"]
edition = "2018"

[dependencies]
bzip2 = "0.3.3"

[profile.release]
lto = true
opt-level = 's'
codegen-units = 1
panic = 'abort'

[build-dependencies]
cc = "1.0.50"